### ISSUE TITLE
Feature request, [Preferred/Common]StockShares* from BS

### ISSUE THREAD

**Issue by ebadi** [HansjoergW/sec-fincancial-statement-data-set#13]
Hello,
I was investigating a bug that causes the outstanding shares (and, as a result, the market cap) to become negative or very close to zero. 
![Screenshot from 2024-10-04 21-42-19](https://github.com/user-attachments/assets/c673ead3-5160-47d0-8717-4b4a2752a533)

I noticed that **OutstandingShares** is part of the Income Statement (IS), while, as mentioned in   [07_04_customize_standardizer.ipynb](https://github.com/HansjoergW/sec-fincancial-statement-data-set/blob/main/notebooks/07_04_customize_standardizer.ipynb) ,   **[Preferred/Common]StockShares**  
is one of the most common tags in the Balance Sheet (BS). Is there a way to incorporate the values from Balance Sheet (BS) into this calculation?

**Comment by ebadi** [comment]
I noticed that the negative values are mistakes in reporting. I also tried my suggestion without major improvement.

Closing this issue

**Comment by ebadi** [comment]
For [this report](https://www.sec.gov/cgi-bin/viewer?action=view&cik=1703956&accession_number=0001437749-24-019495&xbrl_type=v#) the number of share is 54,119,255 but the library extract it from the IS as 53501. I suspect they dropped the last three digits to represent it as thousands (similar to other numbers in the table).  
![Screenshot from 2024-10-05 17-24-00](https://github.com/user-attachments/assets/d4990851-3e93-4085-a86b-1fbb79e03ab7)

Is there a simple way to priorities the number from the cover page ("Document and Entity information" ) or uses the maximum value from different sections?

**Comment by HansjoergW** [comment]
Hi @ebadi 
So, as far as I have seen, OutstandingShares can appear in the CoverPage, the BalanceSheet, and also the IncomeStatement. 

But as I understand, they do not have the same exact meaning. I haven't investigated that, so I am not sure if you can assume that they are the same, resp. close enough to treat them that way. In the CP, the value appears as EntityCommonStockSharesOutstanding (if present), in the Balance Sheet as CommonStockSharesOutstanding, and in the IncomeStatement as WeightedAverageNumberOfSharesOutstandingBasic.

I also noticed that the value in the IncomeStatement is often reported incorrectly, so that is off by a factor of 1000.

For your purpose, I assume that you will anyway put all the data for IS, BS, and CF into one table, so that you also can calculate financial ratios that uses columns from different tables (like ReturnOnEquity, ReturnOnAssets, DividendPayoutRatio, ...), so you could do the following.

Add the EntityCommonStockSharesOutstanding  information from the CP as an additional column.
- In the 06_bulk_data_processing_deep_dive, I added the preparation for the CP dataset (only in the branch "automation" yet"). You could use that one and add the value EntityCommonStockSharesOutstanding  by using the tags adsh, tag, version, coreg, ddate, and qtrs as index. I haven't checked, but I assume these entries will be unique.

- configure the BSStandardizer according to 07_04_customize_standardizer, so that the CommonStockSharesOutstanding is also added to the final output.
- then calculate your final "Shares" column according to your needs.

I will add it to my ideas list, but I am not sure yet, how and when I will integrate it directly.

**Comment by ebadi** [comment]
Thanks for the explanation. Yes, it makes sense. I will check the  "automation" branch as soon as I find the time
