### ISSUE TITLE
Question: tabular representation of a report

### ISSUE THREAD

**Issue by ebadi** [HansjoergW/sec-fincancial-statement-data-set#8]
I aim to train a ML model to predict future financial reports based on historical data. To achieve this, I need a tabular representation of the financial statements, as follows:

-  tabular representation of financial statement with this structure: 
```
cik, period_start_date, period_length,  ...,
    IS_col1, IS_col2, ..., IS_colx, 
    CF_col1, CF_col2, ... CF_colx,
    BS_col1, BS_col2, ...BS_colx
```
- period_start_date, period_length, cik as the key.
- standardized CF, IS for the specified reporting period. 
- standardized BS reports are for the time point = period_start_date + period_length

related to https://github.com/HansjoergW/sec-fincancial-statement-data-set/issues/5#issuecomment-2274358132

**Comment by HansjoergW** [comment]
I think it would be better to think of "enddate" instead of period start_date, since this is the date, of the report.

So I would
cik, ddate, qtrs_is_cf, is_cols.. , cf_cols, bs_cols

ddate is the endate of the period, qtrs is the period length in qtrs  (but only relevant for IS und CF).

As written in the other thread, for IS and CF you need to join on qtrs and ddate, but for BS, you just need to join on ddate.

**Comment by ebadi** [comment]
Thanks for the post.

**Comment by HansjoergW** [comment]
Hi @ebadi 

Yes, `date` is a real date format, so that can be easily used when plotting. I kept `ddate` since it is just an integer and we only have "end-of-months-dates". Hence, date-calculations are probably a little faster, if I do them directly as int, instead of converting all the `ddate` to a real date format and don't the operations with the datetime API. However, I didn't measure it. Moreover, the `ddate` could also be removed for the final standardized presentation.

Indeed, it would make sense to add `filed` to the final result. I mean, you could create a hashmap with adsh as key and filed as value by reading all sub_txt files and then merging that into final result.

However, as a quick solution, I would suggest you write your own the "presenting" method. 

Just extract it from the standardizing logic, and use as input the dataframe and the standardized you want to use. Something like that:

````
    def present(standardizer,  databag: JoinedDataBag) -> pd.DataFrame:

        standardized_df = standardizer.process(databag.pre_num_df)

        data_to_merge_df = databag.sub_df[['adsh', 'cik', 'form', 'fye', 'fy', 'fp', 'filed']].copy()

        # The name of a company can change during its liftime. However, we want to have the
        # same name for the same cik in all entries. Therefore, we first have to find the
        # latest name of the company.

        # first, create a cik-name look up table,
        df_latest = (databag.sub_df[['cik', 'name', 'period']].sort_values('period')
                     .drop_duplicates('cik', keep='last'))

        # Create the dictionary
        cik_name_dict = dict(zip(df_latest['cik'], df_latest['name']))

        data_to_merge_df['name'] = data_to_merge_df['cik'].map(cik_name_dict)

        merged_df = pd.merge(data_to_merge_df, standardized_df, on='adsh', how='inner')

        # create the date column and sort by date
        merged_df['date'] = pd.to_datetime(merged_df['ddate'], format='%Y%m%d')

        # sort the columns
        merged_df = merged_df[['adsh', 'cik', 'name', 'form', 'fye', 'fy', 'fp', 'date'] +
                              standardized_df.columns.tolist()[1:]]

        result = merged_df.sort_values(by='date')

        # store it in the standardizer object as new result
        standardizer.result = result

        return result
       ````
 You could also write your own subclasses of the three standardizer and overwrite the present method or implement your own.

In order to add additional tags, you would need write your own Standardizer.

So you basically copy the code of the BS,IS, or CF standardizer and if you just want to add a new tag (if we assume that the tag is very common and widely used) you could jus add the tagname to the "final_tags" definition

**Comment by ebadi** [comment]
Thanks for the explanation.

Adding `filed` column : Updating `standardizing.py` as you suggested did the trick:
```
        data_to_merge_df = databag.sub_df[['adsh', 'cik', 'form', 'fye', 'fy', 'fp', 'filed']].copy()
```
and not to forget this line as well: 
```
        merged_df = merged_df[['adsh', 'cik', 'name', 'form', 'fye', 'fy', 'fp', 'date', 'filed'] +
                              standardized_df.columns.tolist()[1:]]
```

Adding new tag: adding 'NumberOfSharesIssued' to `final_tags`  solved my issue as well. I used https://www.ifrs.org/content/dam/ifrs/standards/taxonomy/2024/taxonomy-illustrated/taxonomy-iti-2024-by-fs.xlsx and https://github.com/Nneoma-Ihueze/SEC-Mapping/blob/main/xbrl_to_fin-statement_mapping.json to find the right name for the tag.

**Comment by ebadi** [comment]
I modified my package and added `NumberOfSharesIssued` to the `final_tags` but now noticed that the `NumberOfSharesIssued` contains only 0. Any idea how to fix this?

**Comment by HansjoergW** [comment]
@ebadi I have to look into it. The tag names should be WeightedAverageNumberOfSharesOutstandingBasic and WeightedAverageNumberOfDilutedSharesOutstanding. But just adding them doesn't work. I will let you know when I found time to have a look at the problem

**Comment by HansjoergW** [comment]
@ebadi I found the problem, but i will need to create a new minor version for it.

**Comment by ebadi** [comment]
Thank you so much. I would also appreciate if you document how you find these tag names. I am using this [excel sheet](https://www.ifrs.org/content/dam/ifrs/standards/taxonomy/2024/taxonomy-illustrated/taxonomy-iti-2024-by-fs.xlsx) and I cannot find WeightedAverageNumberOfSharesOutstandingBasic and WeightedAverageNumberOfDilutedSharesOutstanding there.

**Comment by HansjoergW** [comment]
@ebadi 
In order to find used tags, go to the SEC Edgar page and open a report. E.g. https://www.sec.gov/cgi-bin/browse-edgar?CIK=0000320193&owner=exclude and the selecting the "interactive data" of a 10-Q or 10-K.

Then select the "Financial Statements" Section and choose a statement. Select the position you are interested in expand the "Details" as shown here:
![image](https://github.com/user-attachments/assets/a3bd1da2-9919-46d9-a342-8858ee529bdd)

Instead of using "interactive data", you can also open the "document" and then browse the section with the financial statement. You can click on any value in the document to get the details of that position.

When having a tag name, you can also ask ChatGPT if there are other tags referencing the same/similar position, or if that tag belongs to "Hierarchy". ChatGPT often comes up with good answers, but you still have to check if these tags really exist in the data.

And of course, there is also the official documentation for the standard which can be browsed online. But I haven't really used that.

**Comment by HansjoergW** [comment]
@ebadi i released a new version 1.6.1

**Comment by ebadi** [comment]
Thanks. I just tested it and everything works (except minor changes needed for the missing `uom` column)

**Comment by ebadi** [comment]
- I forgot o thank you for the your clear instruction on how to find the tags. 
- I noticed that there are two columns EarningsPerShareBasic/EarningsPerShareDiluted that can be calculated if we have NetIncomeLos and  WeightedAverageNumberOfSharesOutstandingBasic/WeightedAverageNumberOfDilutedSharesOutstanding. It is up to you to keep the column

**Comment by elias-gi** [comment]
Hello! I am opening this because it seems something has broken over the use of added tags. I'm trying to add WeightedAverageNumberOfSharesOutstandingBasic  / CommonStockSharesOutstanding but neither of them seem to be working.

I use the below code

all_joinedbag:JoinedDataBag = JoinedDataBag.load(target_path=r"path_to_BS")
standarizer = BalanceSheetStandardizer(additional_final_tags=["CommonStockSharesOutstanding"])

# standardize the data
df = all_joinedbag.present(standarizer)
 and i receive the below 
`KeyError: "['CommonStockSharesOutstanding'] not in index"`

I did the value counts of tags and i see it in there:
`all_joinedbag:JoinedDataBag = JoinedDataBag.load(target_path=r"path_to_BS")
counts_df = all_joinedbag.pre_num_df.tag.value_counts()


counts_df = counts_df.to_frame().reset_index()

df = spark.createDataFrame(pd.DataFrame(counts_df))
df.display()` 
(its spark code in the end but doesnt really matter)

Whats wrong with this?

**Comment by HansjoergW** [comment]
@elias-gi 
In the case of the Balance Sheet the CommonStockSharesOutstanding entries are not part of the "main" table but instead are presented within the "parentheses" section. So, they are grouped with an additional "report" number and have the flag "inpth" (in parentheses) set. (In contrary, the WeightedAverageNumberOfSharesOutstandingBasic is part of the main table of the Income statement).

You can use the 03_explore_with_interactive_notebook.ipynb notebook to analyze that. (The following example is from adsh 
0000714562-25-000010)

![Image](https://github.com/user-attachments/assets/bc8cb64a-4e96-4378-abfa-1c339548678c)

and in the "real" report this is visualized as

![Image](https://github.com/user-attachments/assets/c25414ea-3ec7-438a-80a0-474025bcf8ff)

The BSStandardizer only looks at the "main" table, resp. only considers entries with an entry in the "report" column that belongs to the main table.

Therefore, CommonStockSharesOutstanding is not visible to the BalanceSheet Standardizer. 

However, you can create your table that only contains the adsh and the value for the CommonStockSharesOutstanding  and then merge them with the results of the standardized BS.
